paths:
  raw_data: "./data/raw/matches_raw.csv"
  processed_data: "./data/processed/features.csv"

model_params:
  n_estimators: 100
  max_depth: 5
  random_state: 42

training:
  test_size: 0.2
  features: ["home_team_rank", "away_team_form", "head_to_head"]
  target: "result"